### ISSUE TITLE
1.0.0 版本

### ISSUE THREAD

**Issue by CaledoniaProject** [baidu/openrasp#160]
提测时间: 2019.1.4
提测顺序: php7 java php5 管理后台
发布时间: 预计3月底发布

### 功能列表

通用

- [x] 单机配置改为 yaml
- [x] 通过自定义 header，实现应用加固，#151 
- [x] 增加 xss_userinput 算法
- [x] 识别SQL执行中出现的异常
- [x] 支持 agent 异常上报
- [x] JSON 参数支持

Java 版本

- [x] 发生攻击时，可根据堆栈获取源代码（反编译方式）
- [x] 支持 WebLogic 9、10 两个服务器，#66
- [x] 支持 JDK 9 - 11，#141
- [x] 支持 attach 机制，实现试验性的不重启安装支持（暂不支持升级）
- [x] 支持 JBoss wildfly，#125（@左撇子 提供）

PHP 版本

- [x] JSON 库替换为 nlohmann/json
- [x] 支持 PHP 7.3
- [x] 拦截基于 LD_PRELOAD 的命令执行
- [x] 发生攻击时，可根据堆栈获取源代码

**Comment by o0x00** [comment]
棒！
